---
- name: Install Linux GSM
  hosts: localhost
  become: true
  vars:
    packages_dep: [mailx,postfix,curl,wget,tar,bzip2,gzip,unzip,python3,binutils,bc,jq,tmux,glibc.i686,libstdc++,libstdc++.i686]

  tasks:
    - name: PACKAGE MANAGER - Install required packages
      yum:
        name: '{{packages_dep}}'
        state: latest

    - name: Add a new user csgoserver
      user:
        name: csgoserver
        shell: /bin/bash

    - name: Copy install script to user's home
      copy:
        src: /provision/csgoserver
        dest: /home/csgoserver/
        owner: csgoserver
        group: csgoserver
        mode: 0755
      delegate_to: localhost

    - name: Install CS:GO via GSM
      shell: /home/csgoserver/csgoserver auto-install
      args:
        executable: /bin/bash
        chdir: /home/csgoserver/
      become: yes
      become_user: csgoserver

    - name: Copy pre-configured server config with GSLT
      copy:
        src: /provision/csgoserver.cfg
        dest: /home/csgoserver/lgsm/config-lgsm/csgoserver/csgoserver.cfg
        owner: csgoserver
        group: csgoserver
        mode: 0755
      delegate_to: localhost

    - name: Copy pre-configured server config with details of server
      copy:
        src: /provision/server_config
        dest: /home/csgoserver/serverfiles/csgo/cfg/csgoserver.cfg
        owner: csgoserver
        group: csgoserver
        mode: 0755
      delegate_to: localhost

    - name: Copy pre-configured server config with friendly-fire and other tweaks
      copy:
        src: /provision/gamemode_competitive.cfg
        dest: /home/csgoserver/serverfiles/csgo/cfg/gamemode_competitive.cfg
        owner: csgoserver
        group: csgoserver
        mode: 0755
      delegate_to: localhost

    - name: Create csgo service
      copy:
        owner: root
        group: root
        mode: 0755
        src: /provision/csgo.service
        dest: /etc/systemd/system/csgo.service      

    - name: Start csgo service
      systemd:
        enabled: yes
        state: started
        name: csgo
        daemon_reload: yes 